settings:
  react:
    version: detect
env:
  browser: true
  commonjs: true
  es2021: true
  node: true
extends:
  - eslint:recommended
  - plugin:react/recommended
  - prettier # Should go last.
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: latest
plugins:
  - react
rules: {}
