# .prettierrc or .prettierrc.yaml
trailingComma: 'es5'
tabWidth: 2
semi: true
singleQuote: true
overrides:
  - files: "*.md"
    options:
      printWidth: 80
      proseWrap: always
      parser: markdown
